name: soutipai_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  dio: ^3.0.9
  toast: ^0.1.5
  cupertino_icons: ^1.0.2
  image_picker: ^0.5.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Lishu
      fonts:
        - asset: fonts/MaShanZheng-Regular.ttf

  assets:
    - assets/images/result/cloud.png
    - assets/images/result/go_home.png
    - assets/images/result/lamp.png
    - assets/images/result/photo_another.png
    - assets/images/result/text_background.png
    - assets/images/photograph/circle.png
    - assets/images/photograph/flashlight.png
    - assets/images/photograph/goback.png
    - assets/images/photograph/photograph_circle.png
    - assets/images/photograph/photograph_picture.png
    - assets/images/photograph/photograph_storage_frame.png
    - assets/images/photograph/photograph_storage_picture.png