name: soutipai_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  dio: any
  toast: ^0.1.5
  cupertino_icons: ^1.0.2
  extended_image: ^4.2.1
  image_cropper: ^1.4.1
  image_editor: any
  image: any
  image_picker: ^0.8.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Lishu
      fonts:
        - asset: fonts/MaShanZheng-Regular.ttf

  assets:
    - assets/images/result/cloud.png
    - assets/images/result/go_home.png
    - assets/images/result/lamp.png
    - assets/images/result/photo_another.png
    - assets/images/result/text_background.png
    - assets/images/wrong_questions_book/SanXingTing_sus.jpg
    - assets/images/screenshot/2.png
    - assets/images/screenshot/3.png
    - assets/images/screenshot/4.png
    - assets/images/screenshot/5.jpg
    - assets/images/photograph/circle.png
    - assets/images/photograph/flashlight.png
    - assets/images/photograph/goback.png
    - assets/images/photograph/photograph_picture.png
    - assets/images/photograph/photograph_storage_picture.png

    - assets/images/home/flowers.png
